### ISSUE TITLE
Navigate, display dialogs and get Scaffold state without context or Global keys [new feature]

### ISSUE THREAD

**Issue by GIfatahTH** [GIfatahTH/states_rebuilder#105]
In Flutter, almost all side effects need an active `BuildContext`.
* To navigate between screens, you need a `BuildContext` to get the `NavigatorState`.
* To display the dialog boxes, you need a `BuildContext`.
* To show a snackBar, you need a `BuildContext` to get the active `ScaffoldState`.
* ThemeDate, MediaQuery, DatePicker, and many others require the availability of `BuildContext`.

Although it is a very important concept, the availability of `BuildContext` is limited within the `build` method or the state class of a `StatefulWidget`.

`states_rebuilder` manages to always expose an alive BuildContext` and makes it available everywhere, even outside the widget tree.

To get the  active alive `BuildContext` :
```dart
RM.context; 
```
The `BuildContext` exposed by` states_rebuilder` is active in the sense that it continues to update to contain the value of the last added widget specific to` states_rebuilder` (`Injector`,` StateBuilder`, `WhenRebuilder`,` WhenRebuilderOr`).

That said:
* You must define at least one widget of `states_rebuilder` (must be a child of MaterialApp). This is quite obvious because at the end you use `states_rebuilder` to manage the state and you will certainly define a bunch of them.
* The `BuildContext` is an active leaf of the widget tree, so we are 100% sure of getting valid` NavigatorState` and `ScaffoldState` (this is very important. See below).

## Navigation
to get the `NavigatorState` :
```dart
RM.navigator; 

//ex:
onPressed : (){
   RM.navigator.pushNamed('/route');
}
```
## Show dialogs
use the static method `RM.show`:
```dart
RM.show((BuildContext context ){
    //It exposed the active build context
    showDialog(
      context: context,
      builder: (context) {
      return AlertDialog( ... )
    }
}); 
```
## Theme and MediaQuery
to get the `ThemeData` and `MediaQueryData` :
```dart
RM.theme; 
RM.mediaQuery; 
```
## ScaffoldState
To get the `ScaffoldState` : 
```dart
RM.scaffold; 

//ex:
onPressed : (){
   RM.scaffold.showBottomSheet(...const);
   RM.scaffold.openDrawer();
   RM.scaffold.showSnackBar(..);
}
```
To understand what Active `BuildContext` means and how beneficial it is, Let's imagine this scenario.

* Let's say we have two screens. 
* Let's navigate from screen one to screen two;
* Let's call an asyn method and set it to display a SnackBar when completes.
* Let's pop to the first screen before the asyn method completes.
* The time the asyn method completes, an error saying that 'Looking up a deactivated widget's ancestor is unsafe' will be thrown.

This type of error is common when we register a callback that uses a `BuildContext` of a widget that is removed from the widget tree the time the callback is invoked.

With the concept of active "BuildContext" used in "states_rebuilder", when we pop to the first page, the exposed "BuildContext" updates hold the `BuildContext` of the first page, and when the asyn method completes, a `SnackBar` will be displayed from the `Scaffold` of the first page.

by using the active `BuildContext` of `states_rebuilder` you are sure to never see an error saying "Looking up a deactivated widget's ancestor is unsafe".

This is a working demo example of what has been said

```dart

//From outside the widget tree.
void showAlertDialog() {
  RM.show(
    (context) {
      //show method exposed the active BuildContext,
      showDialog(
        context: context,
        builder: (context) {
          return AlertDialog(
            actions: [
              RaisedButton(
                onPressed: () {
                  //Navigation without context
                  RM.navigator.pop();
                  RM.navigator.push(
                    MaterialPageRoute(
                      builder: (c) => Page2(),
                    ),
                  );
                },
                child: Text('Alert Dialog'),
              )
            ],
          );
        },
      );
    },
  );
}

void showSnackBar() async {
  await Future.delayed(Duration(seconds: 3));
  RM.scaffoldState.showSnackBar(SnackBar(content: Text('Hi')));
}

void main() {
  runApp(
    MaterialApp(home: Page1()),
  );
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: StateBuilder(
          observe: () => RM.create(true),
          builder: (_, __) {
            return RaisedButton(
              child: Text('go to page 1'),
              onPressed: showAlertDialog,
            );
          },
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: StateBuilder(
          observe: () => RM.create(0),
          builder: (_, __) => Column(
            children: [
              RaisedButton(
                child: Text('show SnackBar'),
                onPressed: showSnackBar,
              ),
              RaisedButton(
                child: Text('pop'),
                onPressed: () {
                  RM.navigator.pop();
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by amoslai5128** [comment]
Every time I come and check, the code always gets more elegant

**Comment by asarkar1990** [comment]
Am I doing anything wron here ?
`onTap: () async {
                  RM.get<AuthService>().setState(
                        (state) => state.updateStandard(standard),
                        onSetState: (context) => Navigator.of(context).pop(),
                        onError: (context, error) {
                          Scaffold.of(context).hideCurrentSnackBar();
                          Scaffold.of(context).showSnackBar(
                            SnackBar(
                              content: Text('$error'),
                            ),
                          );
                        },
                      );
                },`

It seems like executing the pop() twice .

**Comment by GIfatahTH** [comment]
That is exactly what is expected.

onSetState will be invoked each time the state changes.

To see when onSetState is invoked add a print statement as follows:
```dart
onSetState: (context) {
 print(RM.get<AuthService>());
 Navigator.of(context).pop();
},
```
To pop after updateStandard(standard) completes successfully use 
```dart
onSetState: (context) {
 print(RM.get<AuthService>());
if(RM.get<AuthService>().hasData){
 Navigator.of(context).pop();
}
},
```
or simply :
```dart
RM.get<AuthService>().setState(
                        (state) => state.updateStandard(standard),
                        onData: (context, data) => Navigator.of(context).pop(),
```

You can also await setState method:

```dart
onTap: () async {
                 await  RM.get<AuthService>().setState(
                        (state) => state.updateStandard(standard),
                        onError: (context, error) {
                          Scaffold.of(context).hideCurrentSnackBar();
                          Scaffold.of(context).showSnackBar(
                            SnackBar(
                              content: Text('$error'),
                            ),
                          );
                        },
                      );
 Navigator.of(context).pop();
                },
```

**Comment by asarkar1990** [comment]
Thank you.

**Comment by pMertDogan** [comment]
Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold.
E/flutter (31359): No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
E/flutter (31359): There are several ways to avoid this problem. The simplest is to use a Builder to get a context that is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
E/flutter (31359):   https://api.flutter.dev/flutter/material/Scaffold/of.html
E/flutter (31359): A more efficient solution is to split your build function into several widgets. This introduces a new context from which you can obtain the Scaffold. In this solution, you would have an outer widget that creates the Scaffold populated by instances of your new inner widgets, and then in these inner widgets you would use Scaffold.of().
E/flutter (31359): A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.

Is it possible avoid this problem using RM.scaffold?

BottomSheet > AddSubjectSheet> AddSubjectButton 
if title is empty throw exception. I want show exception using snackbar.But there is a context problem.Can i fix it using RM.scaffold?

```
showModalBottomSheet(
            //enable scroll down to close
            isScrollControlled: true,
            backgroundColor: sheetBGColor,
            shape: ContinuousRectangleBorder(
                borderRadius: BorderRadius.vertical(top: Radius.circular(50))),
            context: context,
            builder: (context) {
              return AddSubjectSheet();
            })
```


```
class AddSubjectSheet extends StatelessWidget {
  const AddSubjectSheet({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      //set bottom sheet height to %90
      height: MediaQuery.of(context).size.height * 0.9,
      child: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            Wrap(
              alignment: WrapAlignment.center,
              crossAxisAlignment: WrapCrossAlignment.center,
              runSpacing: 10,
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.only(top: 8.0),
                  child: Text(
                    "Create a new Subject",
                    style: Theme.of(context)
                        .textTheme
                        .headline4
                        .copyWith(fontSize: 26),
                  ),
                ),
                TitleText(
                  titleText: "Subject picture",
                ),
                AddPhoto(),
                TitleText(
                  titleText: "Subject title",
                ),
                TitleFormField(),
                TitleText(
                  titleText: "Subject explanation",
                ),
                ExplanationFromField(),
                Text(
                  "Timeline",
                  style: TextStyle(color: Colors.amber, fontSize: 18),
                ),
                StartEndTimeLineUI(),
                TitleText(
                  titleText: "Where?",
                ),
                Location(),
                TitleText(
                  titleText: "Add contributor",
                ),
                ContributorsSelect(),
                TagsAddOrSelect(),
                TitleText(
                  titleText: "Priority",
                ),
                PrioritySlider(),
                AddNewToDoUI(),
                AddNewSubjectButton(),
              ],
            ), //Keyboard height as padding for let user see fields
            KeyboardPadding()
          ],
        ),
      ),
    );
  }
}
```

```

class AddNewSubjectButton extends StatelessWidget {
  const AddNewSubjectButton({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Builder(
        builder: (contextBuilder) => InkWell(
          onTap: () {
            final subjectVM = RM.get<SubjectVM>();
            final a = RM.get<AddSubjectVM>();
            if (!subjectVM.isWaiting) {
              subjectVM.setState(
                (s) async {
                  a.state.addTagsToSubject();
                  await s.addSubject(a.state.subject);
                  //remove tags for new subjects
                  a.state.clearFields();
                },
                onData: (_, __) => Navigator.pop(context),
                onError: (context, error) {
                  RM.scaffold.showSnackBar(SnackBar(
                    content: Text(error.toString()),
                  ));
                },
              );
            }
          },
          child: AnimatedContainer(
            duration: Duration(milliseconds: 250),
            decoration: BoxDecoration(
                color: UIColors.todoOrange,
                borderRadius: BorderRadius.circular(8)),
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 30),
              child: StateBuilder<SubjectVM>(
                observe: () => RM.get<SubjectVM>(),
                builderWithChild: (context, subjectVMRM, child) {
                  return subjectVMRM.isWaiting
                      ? OrangeLoadingIndicator()
                      : child;
                },
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Text(
                      "All is well",
                      style: TextStyle(fontSize: 25, color: Colors.white),
                    ),
                    Icon(
                      Icons.check,
                      color: Colors.green,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by GIfatahTH** [comment]
@pMertDogan  thanks for reporing the issue.

>Is it possible avoid this problem using RM.scaffold?

You have to use the latest version of states_rebuildler and try.

```dart
  final subjectVM = RM.get<SubjectVM>();
            final a = RM.get<AddSubjectVM>();
            if (!subjectVM.isWaiting) {
              subjectVM.setState(
                (s) async {
                  a.state.addTagsToSubject();
                  await s.addSubject(a.state.subject);
                  //remove tags for new subjects
                  a.state.clearFields();
                },
                onData: (_, __) => Navigator.pop(context),
                onError: (context, error) {
                  RM.scaffold.showSnackBar(SnackBar(
                    content: Text(error.toString()),
                  ));
                },
              );
            }
          },
```

Here I see you are using RM.scaffold.showSnackBar? 

try using the contextBuilder.

Scaffold.of(contextBuilder).showSnackBar!


For the information you provide I can not replicate your case and can not guess why there is not Scaffold parent of the widget where the showSnackBar is called?

**Comment by pMertDogan** [comment]
Hi,
I already tried contextBuilder option. But i cant make it work. I tried again but still not working

Here you can check project here. 
https://github.com/pMertDogan/yap
```

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold.
E/flutter ( 6653): No Scaffold ancestor could be found starting from the context that was passed to Scaffold.of(). This usually happens when the context provided is from the same StatefulWidget as that whose build function actually creates the Scaffold widget being sought.
E/flutter ( 6653): There are several ways to avoid this problem. The simplest is to use a Builder to get a context that is "under" the Scaffold. For an example of this, please see the documentation for Scaffold.of():
E/flutter ( 6653):   https://api.flutter.dev/flutter/material/Scaffold/of.html
E/flutter ( 6653): A more efficient solution is to split your build function into several widgets. This introduces a new context from which you can obtain the Scaffold. In this solution, you would have an outer widget that creates the Scaffold populated by instances of your new inner widgets, and then in these inner widgets you would use Scaffold.of().
E/flutter ( 6653): A less elegant but more expedient solution is assign a GlobalKey to the Scaffold, then use the key.currentState property to obtain the ScaffoldState rather than using the Scaffold.of() function.
E/flutter ( 6653): The context used was:
E/flutter ( 6653):   Builder
E/flutter ( 6653): #0      Scaffold.of (package:flutter/src/material/scaffold.dart:1456:5)
E/flutter ( 6653): #1      AddNewSubjectButton.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:todo/widgets/addSubjectSheet/addNewSubjectButton.dart:32:28)
E/flutter ( 6653): #2      ReactiveModelImp.setState.<anonymous closure> (package:states_rebuilder/src/reactive_model_imp.dart:278:18)
E/flutter ( 6653): #3      ReactiveModelImp.setState._rebuildStates.<anonymous closure> (package:states_rebuilder/src/reactive_model_imp.dart:317:29)
E/flutter ( 6653): #4      StatesRebuilder.rebuildStates.<anonymous closure> (package:states_rebuilder/src/states_rebuilder.dart:173:29)
E/flutter ( 6653): #5      StateBuilderState.update (package:states_rebuilder/src/state_builder.dart:307:17)
E/flutter ( 6653): #6      StatesRebuilder.rebuildStates (package:states_rebuilder/src/states_rebuilder.dart:168:18)
E/flutter ( 6653): #7      ReactiveModelImp.setState._rebuildStates (package:states_rebuilder/src/reactive_model_imp.dart:315:9)
E/flutter ( 6653): #8      ReactiveModelImp.setState._onErrorCallBack (package:states_rebuilder/src/reactive_model_imp.dart:377:21)
E/flutter ( 6653): #9      ReactiveModelImp.setState.<anonymous closure> (package:states_rebuilder/src/reactive_model_imp.dart:415:29)
E/flutter ( 6653): #10     _rootRunBinary (dart:async/zone.dart:1204:38)
E/flutter ( 6653): #11     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
E/flutter ( 6653): #12     _CustomZone.runBinaryGuarded (dart:async/zone.dart:995:7)
E/flutter ( 6653): #13     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter ( 6653): #14     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:16)
E/flutter ( 6653): #15     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:275:7)
E/flutter ( 6653): #16     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:783:19)
E/flutter ( 6653): #17     _StreamController._addError (dart:async/stream_controller.dart:663:7)
E/flutter ( 6653): #18     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:180:18)
E/flutter ( 6653): #19     _rootRunBinary (dart:async/zone.dart:1204:38)
E/flutter ( 6653): #20     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
E/flutter ( 6653): #21     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
E/flutter ( 6653): #22     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter ( 6653): #23     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter ( 6653): #24     Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 6653): #25     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
E/flutter ( 6653): #26     AddNewSubjectButton.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:todo/widgets/addSubjectSheet/addNewSubjectButton.dart)
E/flutter ( 6653): <asynchronous suspension>
E/flutter ( 6653): #27     AddNewSubjectButton.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:todo/widgets/addSubjectSheet/addNewSubjectButton.dart)
E/flutter ( 6653): #28     ReactiveModelImp.setState (package:states_rebuilder/src/reactive_model_imp.dart:401:33)
E/flutter ( 6653): #29     AddNewSubjectButton.build.<anonymous closure>.<anonymous closure> (package:to

```

**Comment by GIfatahTH** [comment]
The idea here is that showModalBottomSheet routes to new page where Scaffold is not available. To fix try
```dart
showModalBottomSheet(
            //enable scroll down to close
            isScrollControlled: true,
            backgroundColor: sheetBGColor,
            shape: ContinuousRectangleBorder(
                borderRadius: BorderRadius.vertical(top: Radius.circular(50))),
            context: context,
            builder: (context) {
              return SizedBox(
                  height: MediaQuery.of(context).size.height * 0.9,
                   child: Scaffold(
                        body: AddSubjectSheet(),
                        backgroundColor: Colors.transparent,
                   ),
              );
            })
```

**Comment by pMertDogan** [comment]
Thanks,its works. 

Is it possible to fix RM.scaffold to get correct Context with Scaffold? (HomeScreen.dart Scaffold)

**Comment by GIfatahTH** [comment]
This is how flutter works, it has nothing to do with states_rebuilder. Even if you mange to get a context with scaffold, no snackbar will be displayed because the top page is showModalBottomSheet which has no scaffold.


By the way I like the way you are using states_rebuilder.

**Comment by pMertDogan** [comment]
Yes, it's flutter releated problem. 

Thanks, your package help me alot . Many tutorial from author and i can get answers to my questions easliy. :)
