### ISSUE TITLE
Exception not being correctly handled 

### ISSUE THREAD

**Issue by thedude61636** [GIfatahTH/states_rebuilder#137]
I have a repo which simply throws an error if a condition is met

```
class FakeUserRepo implements IUserRepo {
  User user;

  bool get isLoggedIn => user != null;

  @override
  Future<User> login({String email, String password}) async {
    await Future.delayed(Duration(seconds: 3));

    if (email == "@" && password == "1234") {
      this.user = User()
        ..password = password
        ..email = email
        ..apiToken = "apitoken";
      return user;
    } else if(password=="123" && email=="@"){
      print("THROWING ERROR");
      throw Exception("ERROR LOGIN");
    }
    else {
      user = User();
      return this.user;
    }
  }
}

abstract class IUserRepo {
  User user;

  bool get isLoggedIn;

  Future<User> login({String email, String password});
}

```
and a stateful widget 

```
class ExampleScreen extends StatefulWidget {
  @override
  _ExampleScreenState createState() => _ExampleScreenState();
}

class _ExampleScreenState extends State<ExampleScreen> {
  @override
  Widget build(BuildContext context) {
    return StateBuilder<IUserRepo>(
      builder: (context, model) {
        return Scaffold(
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text("Error is  : ${model.error}"),
                Text("User is null : ${model.state.user==null}"),
                Text("CONNECTION STATE: ${model.connectionState} "),
                FlatButton(onPressed: (){

                  model.setState((s) => model.state.login(email: "@",password:"123"));
                }, child: Text("login with error")),
              ],
            ),
          ),
        );
      },
    );
  }
}

```
which i'm using to listen to the repo and react on it
when the error is thrown, the widget isn't rebuilt and i get an error 

```
E/flutter (31718): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: ERROR LOGIN
E/flutter (31718): #0      _SetState.onErrorCallBack (package:states_rebuilder/src/reactive_model/set_state.dart:181:7)
E/flutter (31718): #1      _SetState._futureHandler.<anonymous closure> (package:states_rebuilder/src/reactive_model/set_state.dart:260:11)
E/flutter (31718): #2      _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (31718): #3      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (31718): #4      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
E/flutter (31718): #5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
E/flutter (31718): #6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
E/flutter (31718): #7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
E/flutter (31718): #8      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:812:19)
E/flutter (31718): #9      _StreamController._addError (dart:async/stream_controller.dart:690:7)
E/flutter (31718): #10     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:178:18)
E/flutter (31718): #11     _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (31718): #12     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (31718): #13     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
E/flutter (31718): #14     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
E/flutter (31718): #15     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
E/flutter (31718): #16     Future._completeError (dart:async/future_impl.dart:537:5)
E/flutter (31718): #17     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
E/flutter (31718): #18     FakeUserRepo.login (package:yamama_ecom/data/repos/user_repo.dart)
E/flutter (31718): <asynchronous suspension>
E/flutter (31718): #19     _ExampleScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:yamama_ecom/main.dart:132:53)
E/flutter (31718): #20     _SetState._setStateHandler (package:states_rebuilder/src/reactive_model/set_state.dart:221:33)
E/flutter (31718): #21     _SetState.call (package:states_rebuilder/src/reactive_model/set_state.dart:208:12)
E/flutter (31718): #22     ReactiveModel.setState (package:states_rebuilder/src/reactive_model/reactive_model_base.dart:404:7)
E/flutter (31718): #23     _ExampleScreenState.build.<anonymous closure>.<anonymous closure> (package:yamama_ecom/main.dart:132:25)
E/flutter (31718): #24     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (31718): #25     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (31718): #26     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (31718): #27     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (31718): #28     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (31718): #29     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (31718): #30     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (31718): #31     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (31718): #32     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (31718): #33     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (31718): #34     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (31718): #35     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (31718): #36     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:370:19)
E/flutter (31718): #37     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:350:22)
E/flutter (31718): #38     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:266:11)
E/flutter (31718): #39     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:305:7)
E/flutter (31718): #40     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (31718): #41     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (31718): #42     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (31718): #43     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (31718): #44     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (31718): #45     _invoke1 (d
```
which is apparently from flutter not your package 

if i set the should rebuild in the statebuilder widget then it functions as expected an error is caught and widget is rebuilt 
```
shouldRebuild: (model) {
    return model.hasData || model.isIdle != false || model.hasError;
},
```

but i still get the error in the console and I've tried setting the catchError param in setstate method, and it won't catch the error as well 

and here's a flutter doctor 
```
[√] Flutter (Channel dev, 1.23.0-4.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-4.0.pre at C:\Program Files\Android\flutter
    • Framework revision 83dd176777 (4 days ago), 2020-09-22 12:04:44 -0700
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\TheDude61636\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.0)
    • VS Code at C:\Users\TheDude61636\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Mi 9T Pro (mobile) • d5f65787   • android-arm64  • Android 10 (API 29)
    • Web Server (web)   • web-server • web-javascript • Flutter Tools
    • Chrome (web)       • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

**Comment by thedude61636** [comment]
one more thing  in model.setstate
setting catch error to false results in the console error above 
and passing onError  will remove the console error but will not rebuild widget 
is this the intended behavior or is it an issue?

**Comment by GIfatahTH** [comment]
>one more thing in model.setstate
setting catch error to false results in the console error above
and passing onError will remove the console error

* Exceptions are thrown by default. To catch them you have to set catchError to true or define the onError callback.

> but will not rebuild widget
is this the intended behavior or is it an issue?

* Yes is inhended.

* StateBuilder will rebuild only if the model emits a notifcation with onData state. In case you want to rebuild the widget on all other state use WhenRebuilderOr.  
See this change log:
https://github.com/GIfatahTH/states_rebuilder/blob/master/states_rebuilder_package/changelog/v-3.0.0.md

**Comment by thedude61636** [comment]
Closing as this is correct and intended behavior
