### ISSUE TITLE
InjectedAuth

### ISSUE THREAD

**Issue by cidothia** [GIfatahTH/states_rebuilder#181]
Getting an Unhandled Exception inside the i_auth.dart Line 58

I am just using the code from the Wiki document, and the Issue explaining the InjectedAuth feature.

```text
Launching lib\main.dart on sdk gphone x86 64 arm64 in debug mode...
lib\main.dart:1
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:65527/RLWsMRxpqLA=/ws
W/IInputConnectionWrapper(19112): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(19112): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(19112): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(19112): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(19112): endBatchEdit on inactive InputConnection
E/flutter (19112): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: setState() called after dispose(): _StateBuilderWithoutWatchState<dynamic>#57b6b(lifecycle state: defunct, not mounted)
E/flutter (19112): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (19112): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (19112): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (19112): #0      ReactiveModelCore._setToHasError
package:states_rebuilder/…/reactive_model/reactive_model_core.dart:178
E/flutter (19112): #1      ReactiveModel.setState.call
package:states_rebuilder/…/reactive_model/reactive_model.dart:266
E/flutter (19112): #2      ReactiveModel.setState.call
package:states_rebuilder/…/reactive_model/reactive_model.dart:223
E/flutter (19112): #3      ReactiveModel.setState
package:states_rebuilder/…/reactive_model/reactive_model.dart:319
E/flutter (19112): #4      _AuthService.signIn
package:states_rebuilder/…/injected_auth/i_auth.dart:58
E/flutter (19112): #5      AuthForm.build.<anonymous closure>.<anonymous closure>
package:at_w/…/auth_page/auth_form.dart:78
E/flutter (19112): #6      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:991
E/flutter (19112): #7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
E/flutter (19112): #8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:607
E/flutter (19112): #9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
E/flutter (19112): #10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:230
E/flutter (19112): #11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:475
E/flutter (19112): #12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:93
E/flutter (19112): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:138
E/flutter (19112): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter (19112): #15     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:136
E/flutter (19112): #16     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:122
E/flutter (19112): #17     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:381
E/flutter (19112): #18     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:361
E/flutter (19112): #19     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:278
E/flutter (19112): #20     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:316
E/flutter (19112): #21     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:280
E/flutter (19112): #22     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:238
E/flutter (19112): #23     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:221
E/flutter (19112): #24     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter (19112): #25     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (19112): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (19112): #27     _invoke1 (dart:ui/hooks.dart:180:10)
E/flutter (19112): #28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
E/flutter (19112): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter (19112):
```

**Comment by cidothia** [comment]
Here is a sample that causes the error, but works in every other way.

```dart
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TopAppWidget(
      builder: (c) => MaterialApp(
        navigatorKey: RM.navigate.navigatorKey,
        home: On.auth(onUnsigned: () => AuthPage(), onSigned: () => HomePage())
            .listenTo(
          user,
        ),
      ),
    );
  }
}

final user = RM.injectAuth(
  () => AuthRepo(),
  unsignedUser: UnsignedUser(),
  onSigned: (s) => RM.navigate.toReplacement(HomePage()),
  onUnsigned: () => RM.navigate.toReplacement(AuthPage()),
  onSetState: On.error(
    (err, ref) => AlertDialog(
      title: Text('SignIn Error'),
      content: Text(err),
    ),
  ),
  autoSignOut: (auth) => Duration(hours: auth.expiry),
);

class User {
  const User({
    required this.name,
    this.password = '',
    this.token = '',
    this.expiry = 3,
  });
  final String name;
  final String password;
  final String token;
  final int expiry;
}

class UnsignedUser extends User {
  UnsignedUser() : super(name: 'unsigned');
}

class UserParam {
  const UserParam({
    required this.username,
    required this.password,
    required this.signIn,
    this.signUp,
  });
  final String username;
  final String password;
  final SignIn signIn;
  final SignUp? signUp;
}

enum SignIn {
  api,
}
enum SignUp {
  api,
}

class AuthRepo implements IAuth<User, UserParam> {
  @override
  void dispose() {
    // TODO: implement dispose
  }

  @override
  Future<void> init() async {
    // TODO: implement init
  }

  @override
  Future<User> signIn(UserParam? param) async {
    switch (param!.signIn) {
      case SignIn.api:
        return User(
          name: param.username,
          password: param.password,
          token: 'Yay a Token!',
        );
      default:
        throw UnimplementedError();
    }
  }

  @override
  Future<void> signOut(UserParam? param) {
    // TODO: implement signOut
    throw UnimplementedError();
  }

  @override
  Future<User> signUp(UserParam? param) {
    // TODO: implement signUp
    throw UnimplementedError();
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text('SignIn Successful!'),
    );
  }
}

class AuthPage extends StatelessWidget {
  final _usn = RM.inject<String>(
    () => '',
    middleSnapState: (middleSnap) {
      if (middleSnap.nextSnap.data!.isEmpty) {
        return middleSnap.nextSnap.copyToHasError(
          Exception('Enter a valid username'),
        );
      }
    },
  );
  final _psw = RM.inject<String>(
    () => '',
    middleSnapState: (middleSnap) {
      if (middleSnap.nextSnap.data!.isEmpty) {
        return middleSnap.nextSnap.copyToHasError(
          Exception('Enter a valid password'),
        );
      }
    },
  );
  bool get _isValid => _usn.hasData && _psw.hasData;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          children: [
            On(
              () => TextField(
                onChanged: (value) => _usn.state = value,
              ),
            ).listenTo(_usn),
            On(
              () => TextField(
                onChanged: (value) => _psw.state = value,
              ),
            ).listenTo(_psw),
            OnCombined(
              (s) {
                return ElevatedButton(
                  onPressed: _isValid
                      ? () {
                          user.auth.signIn(
                            (param) => UserParam(
                              username: _usn.state,
                              password: _psw.state,
                              signIn: SignIn.api,
                            ),
                          );
                        }
                      : null,
                  child: Text('SignIn'),
                );
              },
            ).listenTo([
              _usn,
              _psw,
            ]),
          ],
        ),
      ),
    );
  }
}
```

**Comment by GIfatahTH** [comment]
Hi @cidothia, Thank you very much for opening the issue.

When you use `On.auth` you shouldn't use `onSigned` and `onUnsigned` to navigate to `HomePage` and `AuthPage`. Try commenting them.
```dart
final user = RM.injectAuth(
  () => AuthRepo(),
  unsignedUser: UnsignedUser(),
  //Comment these lines
  // onSigned: (s) => RM.navigate.toReplacement(HomePage()),
  // onUnsigned: () => RM.navigate.toReplacement(AuthPage()),
  onSetState: On.error(
    (err, ref) => AlertDialog(
      title: Text('SignIn Error'),
      content: Text(err),
    ),
  ),
  autoSignOut: (auth) => Duration(hours: auth.expiry),
);
```

**Comment by cidothia** [comment]
That fixed it.  Thanks.
