### ISSUE TITLE
[bug] Null check operator used on a null value if onData callback passed to nullable state

### ISSUE THREAD

**Issue by samuelstroschein** [GIfatahTH/states_rebuilder#203]
Hi @GIfatahTH,
I'm am developing again and here comes my first bug report so far 😃 

### Reproduce: 
Modify any test in `injected_nullable_test.dart` to have an `onData` callback like so:

```Dart
  testWidgets(
    'Nullable sync state',
    (tester) async {
      final counter = RM.inject<int?>(
        () => null,
        onData: print,
      );
      expect(counter.state, null);
      counter.state = 0;
      expect(counter.state, 0);
      counter.state = null;
      expect(counter.state, null);
    },
  );
```

The result is:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      InjectedImp.middleSnap (package:states_rebuilder/src/basics/injected_imp.dart:274:36)
#1      InjectedImp._middleSnap (package:states_rebuilder/src/basics/injected_imp.dart:215:7)
#2      InjectedBase.setState.<anonymous closure> (package:states_rebuilder/src/basics/injected_base.dart:82:22)
#3      ReactiveModelBase.setStateFn.<anonymous closure> (package:states_rebuilder/src/basics/reactive_model_base.dart:183:45)
#4      ReactiveModelBase.setStateFn.<anonymous closure> (package:states_rebuilder/src/basics/reactive_model_base.dart:142:12)
#5      InjectedBase.setState (package:states_rebuilder/src/basics/injected_base.dart:135:28)
#6      InjectedBase.state= (package:states_rebuilder/src/basics/injected_base.dart:5:5)
#7      main.<anonymous closure> (file:///Users/samuel/Documents/GitHub.nosync/states_rebuilder/states_rebuilder_package/test/base_test.dart/injected_nullable_test.dart:17:15)
#8      main.<anonymous closure> (file:///Users/samuel/Documents/GitHub.nosync/states_rebuilder/states_rebuilder_package/test/base_test.dart/injected_nullable_test.dart:9:5)
#9      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:156:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Nullable sync state
```

The reason is the following bang operator in `injected_imp.dart`:
```Dart
this.onData?.call(snap.data!);
```
I tried coming up with a solution but this problem seemed to be relatively deep in the middle snap state/I did not want to break anything.

**Comment by GIfatahTH** [comment]
>I'm am developing again and here comes my first bug report so far smiley

Welcome back to development; Hope you are doing well with your studies.

The issue is fixed.

Looking forward for other issues.

**Comment by samuelstroschein** [comment]
Oh well, what a simple fix. Could have come up with it myself!
