### ISSUE TITLE
Error with flutter 3.19 and use of navigation_builder library

### ISSUE THREAD

**Issue by JgomesAT** [GIfatahTH/states_rebuilder#292]
Project can compile because your library use navigation_builder

pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/rm_scaffold.dart:102:3: Error: Expected 0 type arguments.
  PersistentBottomSheetController<T> showBottomSheet<T>(
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/rm_scaffold.dart:124:29: Error: Expected 0 type arguments.
    final r = scaffoldState.showBottomSheet<T>(
                            ^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling file:///Users/jorgegomes/.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/navigation_builder.dart, which contains the type: FunctionType(<invalid> Function<T>(Widget, {backgroundColor: Color?, clipBehavior: Clip?, constraints: BoxConstraints?, elevation: double?, enableDrag: bool?, shape: ShapeBorder?, transitionAnimationController: AnimationController?})).
#0      ProgramCompiler._typeCompilationError (package:dev_compiler/src/kernel/compiler.dart:3678)
#1      ProgramCompiler._newEmitType (package:dev_compiler/src/kernel/compiler.dart:3471)
#2      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:3379)
#3      ProgramCompiler.visitFunctionType (package:dev_compiler/src/kernel/compiler.dart:3731)
#4      ProgramCompiler._emitClassSignature (package:dev_compiler/src/kernel/compiler.dart:1822)
#5      ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:993)
#6      ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:846)
#7      List.forEach (dart:core-patch/growable_array.dart:416)
#8      ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:784)
#9      List.forEach (dart:core-patch/growable_array.dart:416)
#10     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:505)
#11     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#12     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:794)
<asynchronous suspension>
#13     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:654)
<asynchronous suspension>
#14     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1303)
<asynchronous suspension>
Failed to compile application.

**Comment by karnadii** [comment]
check https://github.com/GIfatahTH/navigation_builder/issues/6

or try my patch
```yaml
  states_rebuilder:
    git:
      url: git@github.com:karnadii/states_rebuilder.git
      ref: 3.19-patch
      path: states_rebuilder_package/
```

**Comment by JgomesAT** [comment]
I have an error with this repo:

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by soufianebenyaala** [comment]
![image](https://github.com/GIfatahTH/states_rebuilder/assets/59481648/3e843335-6329-4498-83be-e6baf6007c0d)
