### ISSUE TITLE
Exception ***Injecting an already injected model*** when navigating too quickly

### ISSUE THREAD

**Issue by KhatibFX** [GIfatahTH/states_rebuilder#72]
Stack trace:
```txt
The following _Exception was thrown building SecondRoute:
Exception: ***Injecting an already injected model***
You are injecting the [Example] model which is already injected.
This is not allowed.
If we are sure you want to inject it again, try injecting it with custom name.

If you are testing the widget set [Injector.enableTestMode] to true

The relevant error-causing widget was: 
  SecondRoute file:///Users/ahmedelkhatib/FlutterProjects/flutter_app/lib/main.dart:32:55
When the exception was thrown, this was the stack: 
#0      InjectorState._initState (package:states_rebuilder/src/injector.dart:275:15)
#1      InjectorState.initState (package:states_rebuilder/src/injector.dart:223:5)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
...     Normal element mounting (121 frames)
...
```

Minimal reproducing code:

```dart
import 'package:flutter/material.dart';
import 'package:states_rebuilder/states_rebuilder.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FirstRoute(),
    );
  }
}

class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            // Navigate to second route when tapped.
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondRoute()),
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
        inject: [
          Inject<Example>(() => Example()),
        ],
        builder: (BuildContext context) {
          return Scaffold(
            appBar: AppBar(
              title: Text("Second Route"),
            ),
            body: Center(
              child: RaisedButton(
                onPressed: () {
                  // Navigate back to first route when tapped.
                  Navigator.pop(context);
                },
                child: Text('Go back!'),
              ),
            ),
          );
        });
  }
}

class Example {}

```

pubspec:

```yaml
dependencies:
  flutter:
    sdk: flutter

  # Simple state management
  states_rebuilder: ^1.14.3
```

Flutter doctor:

```txt
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale en-AE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Connected device (3 available)

• No issues found!

```

I am not sure if you would consider this a bug. The bug happens when you click back from second route to first route and then very quickly tap to second route again while the back animation is still playing. Thanks in advance for looking into this, and thanks for this awesome state management solution!

**Comment by GIfatahTH** [comment]
Thank you for opening this issue and thank you again for the minimal reproducing code you provide. This helps me writing a test that reproduces the issue.

This issue will be fixed in the next update.

This is how the test looks. 
```dart
 testWidgets(
      'issue72: rapidly pushing to second page while it is popping to the first page',
      (tester) async {
    BuildContext firstCtx;
    BuildContext secondCtx;
    Widget firstPage() => Builder(
          builder: (context) {
            firstCtx = context;
            return Text('First page');
          },
        );
    Widget secondPage() => Injector(
          inject: [Inject(() => Example ())],
          builder: (context) {
            secondCtx = context;
            return Text('Second page');
          },
        );
    await tester.pumpWidget(MaterialApp(home: firstPage()));
    expect(find.text('First page'), findsOneWidget);
    // Navigate to the second page:
    Navigator.of(firstCtx).push(
      MaterialPageRoute(
        builder: (ctx) {
          return secondPage();
        },
      ),
    );
    await tester.pumpAndSettle();
    expect(find.text('Second page'), findsOneWidget);
    //pop to the first Page,
    Navigator.of(secondCtx).pop();
    await tester.pump();
    expect(find.text('First page'), findsOneWidget);
    //rapidly push to the second page.
    Navigator.of(firstCtx).push(
      MaterialPageRoute(
        builder: (ctx) {
          return secondPage();
        },
      ),
    );
    await tester.pumpAndSettle();
    expect(find.text('Second page'), findsOneWidget);//Here the test fails with Injecting an already injected model exception
  });
```
