### ISSUE TITLE
How to await? 

### ISSUE THREAD

**Issue by pMertDogan** [GIfatahTH/states_rebuilder#98]
Hi,I cant let the code await for operation.I want pop the bottomSheet after operaion.Is my code wrong? Do you have a any  suggest? 

```
InkWell(
        onTap: () async {
          await RM.get<SubjectVM>().setState((s) async {
            final a = RM.get<AddSubjectVM>();
            a.state.addTagsToSubject();
            await s.addSubject(a.state.subject);
          });
          //Pop to close bottomSheet
          Navigator.pop(context);
        },
```
Its not wait,its close before addSubject operation.

Its throw error because bottomSheet closed by Navigator.pop()
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: 
E/flutter (19005): ***No observer is subscribed yet***
E/flutter (19005): | There is no observer subscribed to this observable ReactiveModelImp<AddSubjectVM> model.
E/flutter (19005): | To subscribe a widget you use:
E/flutter (19005): | 1- StateRebuilder for an already defined:
E/flutter (19005): |   ex:
E/flutter (19005): |   StatesRebuilder(
E/flutter (19005): |     observer: () => ReactiveModelImp<AddSubjectVM>instance,
E/flutter (19005): |     builder : ....
E/flutter (19005): |   )
E/flutter (19005): | 2- Injector.get<ReactiveModelImp<AddSubjectVM>>(context : context). for explicit reactivity.
E/flutter (19005): | 3- RM.get<ReactiveModelImp<AddSubjectVM>>(context : context). for implicit reactivity.
E/flutter (19005): | 4- StateRebuilder for new reactive environment:
E/flutter (19005): |   ex:
E/flutter (19005): |   StatesRebuilder<ReactiveModelImp<AddSubjectVM>>(
E/flutter (19005): |     builder : ....
E/flutter (19005): |   )
E/flutter (19005): | 5 - WhenRebuilder, WhenRebuilderOr, OnSetStateListener, StatesWithMixinBuilder are similar to StateBuilder.
E/flutter (19005): | 
E/flutter (19005): | To silent this error you check for the existence of observers before calling [rebuildStates]
E/flutter (19005): | ex:
E/flutter (19005): |  if(hasObservers){
E/flutter (19005): |    rebuildStates()
E/flutter (19005): | }
E/flutter (19005): 
E/flutter (19005): #0      StatesRebuilder.rebuildStates.<anonymous closure> (package:states_rebuilder/src/states_rebuilder.dart:130:9)
E/flutter (19005): #1      StatesRebuilder.rebuildStates (package:states_rebuilder/src/states_rebuilder.dart:160:6)
E/flutter (19005): #2      ReactiveModelImp.setState._rebuildStates (package:states_rebuilder/src/reactive_model_imp.dart:234:9)
E/flutter (19005): #3      ReactiveModelImp.setState._onErrorCallBack (package:states_rebuilder/src/reactive_model_imp.dart:333:21)
E/flutter (19005): #4      ReactiveModelImp.setState (package:states_rebuilder/src/reactive_model_imp.dart:400:23)
E/flutter (19005): #5      ReactiveModelImp.state= (package:states_rebuilder/src/reactive_model_imp.dart:63:5)
E/flutter (19005): #6      InjectorState.initState.<anonymous closure> (package:states_rebuilder/src/injector.dart:200:65)
E/flutter (19005): #7      _ObserverOfStatesRebuilder.update (package:states_rebuilder/src/injector.dart:316:19)
E/flutter (19005): #8      StatesRebuilder.rebuildStates (package:states_rebuilder/src/states_rebuilder.dart:167:18)
E/flutter (19005): #9      ReactiveModelImp.setState._rebuildStates (package:states_rebuilder/src/reactive_model_imp.dart:234:9)
E/flutter (19005): #10     ReactiveModelImp.setState.<anonymous closure> (package:states_rebuilder/src/reactive_model_imp.dart:362:29)
E/flutter (19005): #11     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (19005): #12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (19005): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (19005): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (19005): #15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter (19005): #16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter (19005): #17     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter (19005): #18     new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:177:18)
E/flutter (19005): #19     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (19005): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (19005): #21     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (19005): #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (19005): #23     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (19005): #24     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (19005): #25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter (19005): #26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter (19005): #27     AddNewSubjectButton.build.<anonymous closure>.<anonymous closure> (package:todo/widgets/addSubjectSheet/addNewSubjectButton.dart)
E/flutter (19005): <asynchronous suspension>
E/flutter (19005): #28     AddNewSubjectButton.build.<anonymous closure>.<anonymous closure> (package:todo/widgets/addSubjectSheet/addNewSubjectButton.dart)
E/flutter (19005): #29     ReactiveModelImp.setState (package:states_rebuilder/src/reactive_model_imp.dart:353:33)
E/flutter (19005): #30     AddNewSubjectButton.build.<anonymous closure> (package:todo/widgets/addSubjectSheet/addNewSubjectButton.dart:29:37)
E/flutter (19005): #31     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (19005): #32     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (19005): #33     GestureRecognizer.invokeCallback (package

```

**Comment by GIfatahTH** [comment]
Do you tried onData callback?
```dart
InkWell(
        onTap: () async {
          await RM.get<SubjectVM>().setState((s) async {
            final a = RM.get<AddSubjectVM>();
            a.state.addTagsToSubject();
            await s.addSubject(a.state.subject);
          },
         onData: (_,__) =>Navigator.pop(context);
         );
          //Pop to close bottomSheet
          // Navigator.pop(context);
        },
```

**Comment by pMertDogan** [comment]
onData works thanks

```
InkWell(
        onTap: () {
          RM.get<SubjectVM>().setState((s) async {
            final a = RM.get<AddSubjectVM>();
            a.state.addTagsToSubject();
            await s.addSubject(a.state.subject);
          }, onData: (_, __) => Navigator.pop(context));
        },
```
